### ISSUE TITLE
Floating mouse position map control

### ISSUE THREAD

**Issue by alebinson** [MapColonies/shared-components-deprecated#33]
Add mouse tracking control to shared map component

**Comment by syncush** [comment]
please look at #43

**Comment by syncush** [comment]
Hey, @alebinson you've moved this issue to done, can it be closed? I think it is resolved by #34 #45

**Comment by alebinson** [comment]
Yep think we can mark it as closed(tests still missing) btw #34 and #45 are PR(s), and related to the issue
